nginx:
    restart: always
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    restart: always
    build: ./flask
    links:
        - redis
        - events
    ports:
        - "8080"
node2:
    restart: always
    build: ./flask
    links:
        - redis
        - events
    ports:
        - "8080"
node3:
    restart: always
    build: ./flask
    links:
        - redis
        - events
    ports:
        - "8080"
events:
    restart: always
    build: ./events
    links:
        - redis
    ports:
        - "5555"
redis:
    restart: always
    image: redis
    ports:
        - "6379"